commerce_number_pattern.commerce_number_pattern.*:
  type: config_entity
  label: 'Number pattern'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Pattern type'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_number_pattern.commerce_number_pattern.plugin.[%parent.plugin]

commerce_number_pattern.commerce_number_pattern.plugin.*:
  type: commerce_number_pattern_plugin_configuration

commerce_number_pattern.commerce_number_pattern.plugin.infinite:
  type: commerce_number_pattern_sequential_plugin_configuration

commerce_number_pattern.commerce_number_pattern.plugin.monthly:
  type: commerce_number_pattern_sequential_plugin_configuration

commerce_number_pattern.commerce_number_pattern.plugin.yearly:
  type: commerce_number_pattern_sequential_plugin_configuration

commerce_number_pattern_plugin_configuration:
  type: mapping
  mapping:
    pattern:
      type: string
      label: 'Pattern'
    padding:
      type: integer
      label: 'Padding'

commerce_number_pattern_sequential_plugin_configuration:
  type: commerce_number_pattern_plugin_configuration
  mapping:
    initial_sequence:
      type: integer
      label: 'Initial sequence'
    per_store_sequence:
      type: boolean
      label: 'Per store sequence'
